/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
import java.sql.*;
import javax.swing.*;

public class client_info extends javax.swing.JFrame {

    /**
     * Creates new form client_info
     */
    set_id ob;
    
    ResultSet rs;
    String query;
    String id, name, phone, vision, keyword, search;
    Integer age;
    Double rsph, rcyl, paxis, psph, lcyl, laxis;
    int permission_emp;
    
    public client_info(set_id obj) {
        initComponents();
        label_id_rec.setVisible(false);
        ob = obj;
        permission_emp = ob.employee_perm;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        setIconImage(new ImageIcon(".\\icons\\Icon.png").getImage());
    }
    
    String setkeyword()
    {
        String choice = combobox_search.getSelectedItem().toString();
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = con.createStatement();
            
            try {
                if (choice.compareTo("ID") == 0)
                query = "SELECT client_id from client_info WHERE client_id = '" + textfield_search.getText() + "'";
                
                if(choice.compareTo("Name") == 0)
                    query = "SELECT client_id from client_info WHERE client_name = '" + textfield_search.getText() + "'";
                
                rs = stm.executeQuery(query);
            }
            catch (SQLException sqlExp) {
                String msg = "'" + choice + "' IS NOT INCLUDED IN THE DATABASE";
                JOptionPane.showMessageDialog(null, msg);
            }
            
            if(rs.next()) {
                keyword = rs.getString("client_id");
                
                con.close();
            }
        }
        catch (SQLException sqlExp) {
            JOptionPane.showMessageDialog(null, sqlExp);
        }
        
        return keyword;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button_goback = new javax.swing.JButton();
        label_title = new javax.swing.JLabel();
        button_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        button_viewall = new javax.swing.JButton();
        label_enter = new javax.swing.JLabel();
        textfield_search = new javax.swing.JTextField();
        combobox_search = new javax.swing.JComboBox<>();
        buttion_search = new javax.swing.JButton();
        label_id = new javax.swing.JLabel();
        label_id_rec = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        textbox_name = new javax.swing.JTextField();
        label_phone = new javax.swing.JLabel();
        textbox_phone = new javax.swing.JTextField();
        label_age = new javax.swing.JLabel();
        textbox_age = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        label_vision = new javax.swing.JLabel();
        label_rcyl = new javax.swing.JLabel();
        textbox_psph = new javax.swing.JTextField();
        textbox_lcyl = new javax.swing.JTextField();
        textbox_paxis = new javax.swing.JTextField();
        textbox_rcyl = new javax.swing.JTextField();
        textbox_vision = new javax.swing.JTextField();
        label_lcyl = new javax.swing.JLabel();
        label_psph = new javax.swing.JLabel();
        label_laxis = new javax.swing.JLabel();
        textbox_rsph = new javax.swing.JTextField();
        textbox_laxis = new javax.swing.JTextField();
        label_rsph = new javax.swing.JLabel();
        label_paxis = new javax.swing.JLabel();
        label_opt = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        button_add = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(909, 637));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        button_goback.setBackground(new java.awt.Color(0, 204, 204));
        button_goback.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        button_goback.setText("GO BACK");
        button_goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_gobackActionPerformed(evt);
            }
        });

        label_title.setFont(new java.awt.Font("Cinzel Black", 1, 16)); // NOI18N
        label_title.setForeground(new java.awt.Color(0, 0, 0));
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("MUJNABIN OPTIC'S");
        label_title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_title.setAlignmentY(0.0F);

        button_logout.setBackground(new java.awt.Color(51, 0, 153));
        button_logout.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        button_logout.setText("LOG OUT");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        button_viewall.setBackground(new java.awt.Color(0, 0, 153));
        button_viewall.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_viewall.setText("VIEW ALL");
        button_viewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_viewallActionPerformed(evt);
            }
        });

        label_enter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_enter.setForeground(new java.awt.Color(0, 0, 0));
        label_enter.setText("ENTER:");

        textfield_search.setBackground(new java.awt.Color(255, 255, 255));
        textfield_search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_search.setForeground(new java.awt.Color(0, 0, 0));

        combobox_search.setBackground(new java.awt.Color(255, 255, 255));
        combobox_search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combobox_search.setForeground(new java.awt.Color(0, 0, 0));
        combobox_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name" }));

        buttion_search.setBackground(new java.awt.Color(0, 0, 153));
        buttion_search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttion_search.setText("SEARCH");
        buttion_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttion_searchActionPerformed(evt);
            }
        });

        label_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_id.setForeground(new java.awt.Color(0, 0, 153));
        label_id.setText("ID:");

        label_id_rec.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        label_id_rec.setForeground(new java.awt.Color(0, 0, 0));
        label_id_rec.setText("ID");

        label_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_name.setForeground(new java.awt.Color(0, 0, 153));
        label_name.setText("NAME:");

        textbox_name.setBackground(new java.awt.Color(255, 255, 255));
        textbox_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_name.setForeground(new java.awt.Color(0, 0, 0));

        label_phone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_phone.setForeground(new java.awt.Color(0, 0, 153));
        label_phone.setText("PHONE NUMBER:");

        textbox_phone.setBackground(new java.awt.Color(255, 255, 255));
        textbox_phone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_phone.setForeground(new java.awt.Color(0, 0, 0));

        label_age.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_age.setForeground(new java.awt.Color(0, 0, 153));
        label_age.setText("AGE:");

        textbox_age.setBackground(new java.awt.Color(255, 255, 255));
        textbox_age.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_age.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_id)
                        .addGap(876, 876, 876))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(button_viewall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(107, 107, 107))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_name)
                                    .addComponent(label_phone)
                                    .addComponent(label_enter))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(textfield_search, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(combobox_search, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(buttion_search, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(label_id_rec)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(textbox_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(label_age)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(textbox_age, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(textbox_name))
                                        .addGap(66, 66, 66)))))
                        .addGap(77, 77, 77))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(button_viewall)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttion_search)
                    .addComponent(label_enter)
                    .addComponent(combobox_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id)
                    .addComponent(label_id_rec))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name)
                    .addComponent(textbox_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_phone)
                    .addComponent(textbox_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_age)
                    .addComponent(textbox_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 0, 255));

        label_vision.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_vision.setForeground(new java.awt.Color(0, 0, 153));
        label_vision.setText("VISION:");

        label_rcyl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_rcyl.setForeground(new java.awt.Color(0, 0, 153));
        label_rcyl.setText("RIGHT CYL:");

        textbox_psph.setBackground(new java.awt.Color(255, 255, 255));
        textbox_psph.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_psph.setForeground(new java.awt.Color(0, 0, 0));

        textbox_lcyl.setBackground(new java.awt.Color(255, 255, 255));
        textbox_lcyl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_lcyl.setForeground(new java.awt.Color(0, 0, 0));

        textbox_paxis.setBackground(new java.awt.Color(255, 255, 255));
        textbox_paxis.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_paxis.setForeground(new java.awt.Color(0, 0, 0));

        textbox_rcyl.setBackground(new java.awt.Color(255, 255, 255));
        textbox_rcyl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_rcyl.setForeground(new java.awt.Color(0, 0, 0));

        textbox_vision.setBackground(new java.awt.Color(255, 255, 255));
        textbox_vision.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_vision.setForeground(new java.awt.Color(0, 0, 0));

        label_lcyl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_lcyl.setForeground(new java.awt.Color(0, 0, 153));
        label_lcyl.setText("LEFT CYL:");

        label_psph.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_psph.setForeground(new java.awt.Color(0, 0, 153));
        label_psph.setText("POWER SPH:");

        label_laxis.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_laxis.setForeground(new java.awt.Color(0, 0, 153));
        label_laxis.setText("LEFT AXIS:");

        textbox_rsph.setBackground(new java.awt.Color(255, 255, 255));
        textbox_rsph.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_rsph.setForeground(new java.awt.Color(0, 0, 0));

        textbox_laxis.setBackground(new java.awt.Color(255, 255, 255));
        textbox_laxis.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_laxis.setForeground(new java.awt.Color(0, 0, 0));

        label_rsph.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_rsph.setForeground(new java.awt.Color(0, 0, 153));
        label_rsph.setText("RIGHT SPH:");

        label_paxis.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_paxis.setForeground(new java.awt.Color(0, 0, 153));
        label_paxis.setText("POWER AXIS:");

        label_opt.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        label_opt.setForeground(new java.awt.Color(0, 0, 0));
        label_opt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_opt.setText("OPTHAMOLOGICAL INFORMATION");
        label_opt.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_opt.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_paxis)
                            .addComponent(label_rsph))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textbox_rsph, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textbox_paxis, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label_lcyl)
                        .addGap(33, 33, 33)
                        .addComponent(textbox_lcyl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label_vision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textbox_vision, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(label_laxis)
                                .addGap(37, 37, 37)
                                .addComponent(textbox_laxis, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(label_rcyl)
                                .addGap(33, 33, 33)
                                .addComponent(textbox_rcyl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(label_psph)
                                .addGap(27, 27, 27)
                                .addComponent(textbox_psph, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(label_opt))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_opt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_rsph)
                    .addComponent(textbox_rsph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_rcyl)
                    .addComponent(textbox_rcyl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_paxis)
                    .addComponent(textbox_paxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_psph)
                    .addComponent(textbox_psph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_vision)
                    .addComponent(textbox_vision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_lcyl)
                    .addComponent(textbox_lcyl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_laxis)
                    .addComponent(textbox_laxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        button_add.setBackground(new java.awt.Color(51, 0, 153));
        button_add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_add.setText("ADD NEW CLIENT");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        button_update.setBackground(new java.awt.Color(51, 0, 153));
        button_update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_update.setText("UPDATE INFORMATION");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        button_delete.setBackground(new java.awt.Color(51, 0, 153));
        button_delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_delete.setText("REMOVE CLIENT");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77)
                .addComponent(button_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addComponent(button_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_delete)
                    .addComponent(button_update)
                    .addComponent(button_add))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(button_goback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_logout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_goback)
                    .addComponent(button_logout))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_gobackActionPerformed
        // TODO add your handling code here:
        dispose();

        homepage ob_home = new homepage(ob);
        ob_home.show();
        
    }//GEN-LAST:event_button_gobackActionPerformed

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        // TODO add your handling code here:
        dispose();

        login_main obj = new login_main();
        obj.show();
    }//GEN-LAST:event_button_logoutActionPerformed

    private void button_viewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_viewallActionPerformed
        // TODO add your handling code here:
        if (permission_emp == 1)
        {
            dispose();

            viewer_client obj = new viewer_client(ob);
            obj.show();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "YOU DO NOT HAVE ACCESS");
        }
        
    }//GEN-LAST:event_button_viewallActionPerformed

    private void buttion_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttion_searchActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = con.createStatement();
            search = setkeyword();

            query = "SELECT * from client_info WHERE client_id = '" + search + "'";
            rs = stm.executeQuery(query);

            if (rs.next()){
                id = rs.getString("client_id");
                name = rs.getString("client_name");
                phone = rs.getString("client_phone_num");
                age = rs.getInt("age");
                vision = rs.getString("vision");
                rsph = rs.getBigDecimal("right_sph").doubleValue();
                rcyl = rs.getBigDecimal("right_cyl").doubleValue();
                paxis = rs.getBigDecimal("power_axis").doubleValue();
                psph = rs.getBigDecimal("power_sph").doubleValue();
                lcyl = rs.getBigDecimal("left_cyl").doubleValue();
                laxis = rs.getBigDecimal("left_axis").doubleValue();
                

                label_id_rec.setText(id);
                label_id_rec.setVisible(true);
                textbox_name.setText(name);
                textbox_phone.setText(phone);
                textbox_vision.setText(String.valueOf(vision));
                
                if (age.equals(0))
                    textbox_age.setText(" ");
                else
                   textbox_age.setText(String.valueOf(age)); 
                
                if (rsph.equals(0.0))
                    textbox_rsph.setText(" "); 
                else
                   textbox_rsph.setText(String.valueOf(rsph)); 
                
                if (rcyl.equals(0.0))
                    textbox_rcyl.setText(" ");
                else
                   textbox_rcyl.setText(String.valueOf(rcyl)); 
                
                if (paxis.equals(0.0))
                    textbox_paxis.setText(" ");
                else
                   textbox_paxis.setText(String.valueOf(paxis)); 
                
                if (psph.equals(0.0))
                    textbox_psph.setText(" ");
                else
                   textbox_psph.setText(String.valueOf(psph)); 
                
                if (lcyl.equals(0.0))
                    textbox_lcyl.setText(" "); 
                else
                   textbox_lcyl.setText(String.valueOf(lcyl)); 
                
                if (laxis.equals(0.0))
                    textbox_laxis.setText(" ");
                else
                   textbox_laxis.setText(String.valueOf(laxis)); 
                
            }

            con.close();

        }
        catch (SQLException sqlExp) {
            JOptionPane.showMessageDialog(null, sqlExp);
        }
    }//GEN-LAST:event_buttion_searchActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:
        try {
            name = textbox_name.getText();
            phone = textbox_phone.getText();
            vision = textbox_vision.getText();
            
            if (textbox_age.getText().isBlank() == true)
                age = 0;
            else
                age = Integer.parseInt(textbox_age.getText());
            
            if (textbox_rsph.getText().isBlank() == true)
                rsph = 0.0;
            else
                rsph = Double.parseDouble(textbox_rsph.getText());
            
            if (textbox_rcyl.getText().isBlank() == true)
                rcyl = 0.0;
            else
                rcyl = Double.parseDouble(textbox_rcyl.getText());
            
            if (textbox_paxis.getText().isBlank() == true)
                paxis = 0.0;
            else
                paxis = Double.parseDouble(textbox_paxis.getText());
            
            if (textbox_psph.getText().isBlank() == true)
                psph = 0.0;
            else
                psph = Double.parseDouble(textbox_psph.getText());
            
            if (textbox_lcyl.getText().isBlank() == true)
                lcyl = 0.0;
            else
                lcyl = Double.parseDouble(textbox_lcyl.getText());
            
            if (textbox_laxis.getText().isBlank() == true)
                laxis = 0.0;
            else
                laxis = Double.parseDouble(textbox_laxis.getText());
                
            search = setkeyword();

            if (name.equals("") || phone.equals(""))
            JOptionPane.showMessageDialog(null, "NAME/PHONE NUMBER CANNOT BE EMPTY");

            else
            {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
                Statement stm = con.createStatement();
                stm.execute("SET FOREIGN_KEY_CHECKS=0");

                query = "UPDATE `client_info` SET `client_id` = '" + id + "',`client_name` = '" + name + "',`client_phone_num` = '" + phone + "',`age` = " + String.valueOf(age) + ",`vision` = '" + vision + "',`right_sph` = " + String.valueOf(rsph) + ",`right_cyl` = " + String.valueOf(rcyl) + ",`power_axis` = " + String.valueOf(paxis) + ",`power_sph` = " + String.valueOf(psph) + ",`left_cyl` = " + String.valueOf(lcyl) + ",`left_axis` = " + String.valueOf(laxis) + " WHERE client_id = '" + search + "'";
                stm.executeUpdate(query);

                stm.execute("SET FOREIGN_KEY_CHECKS=1");
                con.close();

                JOptionPane.showMessageDialog(null, "CHANGES SAVED");
            }
        }
        catch (SQLException sqlExp) {
            JOptionPane.showMessageDialog(null, sqlExp);
        }
    }//GEN-LAST:event_button_updateActionPerformed

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        // TODO add your handling code here:
        settingID();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = null;
                                    
            if (textbox_name.getText().length()==0 || textbox_phone.getText().length()==0) {
                JOptionPane.showMessageDialog(null, "NAME/PHONE NUMBER ARE REQUIRED");
            }
            
            else if (client_check() == true){
                JOptionPane.showMessageDialog(null,"CLIENT ALREADY EXISTS");
            }
            
            else {
                    name = textbox_name.getText();
                    phone = textbox_phone.getText();
                    vision = textbox_vision.getText();

                    if (textbox_age.getText().isBlank() == true)
                        age = 0;
                    else
                        age = Integer.parseInt(textbox_age.getText());

                    if (textbox_rsph.getText().isBlank() == true)
                        rsph = 0.0;
                    else
                        rsph = Double.parseDouble(textbox_rsph.getText());

                    if (textbox_rcyl.getText().isBlank() == true)
                        rcyl = 0.0;
                    else
                        rcyl = Double.parseDouble(textbox_rcyl.getText());

                    if (textbox_paxis.getText().isBlank() == true)
                        paxis = 0.0;
                    else
                        paxis = Double.parseDouble(textbox_paxis.getText());

                    if (textbox_psph.getText().isBlank() == true)
                        psph = 0.0;
                    else
                        psph = Double.parseDouble(textbox_psph.getText());

                    if (textbox_lcyl.getText().isBlank() == true)
                        lcyl = 0.0;
                    else
                        lcyl = Double.parseDouble(textbox_lcyl.getText());

                    if (textbox_laxis.getText().isBlank() == true)
                        laxis = 0.0;
                    else
                        laxis = Double.parseDouble(textbox_laxis.getText());

                    String add_client = "INSERT INTO `client_info`(`client_id`, `client_name`, `client_phone_num`, `age`, `vision`, `right_sph`, `right_cyl`, `power_axis`, `power_sph`, `left_cyl`, `left_axis`) VALUES ('" + id + "', '" + name + "', '" + phone + "', " + String.valueOf(age) + ", '" + vision + "', " + String.valueOf(rsph) + ", " + String.valueOf(rcyl) + ", " + String.valueOf(paxis) + ", " + String.valueOf(psph) + ", " + String.valueOf(lcyl) + ", " + String.valueOf(laxis) + ")";
                    stm = con.createStatement();
                    stm.executeUpdate(add_client);
                    
                    label_id_rec.setText(id);                    
                    String msg = "SIGN UP SUCCESSFUL!\nCLIENT ADDED TO DATABASE\nCLIENT ID: " + id;
                    JOptionPane.showMessageDialog(null,msg);                    
                    label_id_rec.setVisible(true);

                    con.close();
            }
        }
            
        catch(SQLException sqlExp) {
            JOptionPane.showMessageDialog(null,"DATABASE CONNECTION FAILED");
        }
        catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(null,"SIGNUP FAILED");
        }
    }//GEN-LAST:event_button_addActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:
        int delcon = JOptionPane.showConfirmDialog(null,"ARE YOU SURE?"); 
        
        if(delcon == JOptionPane.YES_OPTION){
            try{
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
                Statement stm = con.createStatement();
                stm.execute("SET FOREIGN_KEY_CHECKS=0");
                search = setkeyword();

                query = "DELETE FROM `client_info` WHERE client_id = '" + search + "'";
                stm.executeUpdate(query);

                stm.execute("SET FOREIGN_KEY_CHECKS=1");
                con.close();

                JOptionPane.showMessageDialog(null, "CLIENT REMOVED FROM STORE DATABASE");

                client_info main = new client_info(ob);
                main.setVisible(true);
                this.dispose();
            }
            catch (SQLException sqlExp) {
                JOptionPane.showMessageDialog(null, sqlExp);
            }
        }
        
    }//GEN-LAST:event_button_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    boolean client_check()
    {
        int x = 0;
        try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
                PreparedStatement stm;
                ResultSet rs;

                String name_given = textbox_name.getText();
                String phone_given = textbox_phone.getText();

                stm = con.prepareStatement("Select client_name, client_phone_num from client_info where client_name = ? and client_phone_num = ?");

                stm.setString(1, name_given);
                stm.setString(2, phone_given);
                rs = stm.executeQuery();

                if (rs.next()) {
                    con.close();    
                    x = 1;                    
                }
                
                else
                {
                    x = 0;
                }
            
            }
        catch (SQLException sqlExp) {
            JOptionPane.showMessageDialog(null,"DATABASE CONNECTION FAILED");
        }
        
        if (x == 1) {
            return true;                    
        } 
        else {
            return false;
        }
    }
    
    void settingID()
    {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = (Statement) con.createStatement();
            ResultSet rs;
                 
            rs = stm.executeQuery("SELECT MAX(`client_id`) FROM `client_info`");
            rs.next();
            
            String set_id_str;
            set_id_str = rs.getString(1);
            
            String sub_set_id_str = set_id_str.substring(1);                
            int new_id = Integer.parseInt(sub_set_id_str) + 1;
            id = "C" + String.valueOf(new_id);
            
        }
        catch(SQLException sqlExp) {
            JOptionPane.showMessageDialog(null,"DATABASE CONNECTION FAILED");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttion_search;
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_goback;
    private javax.swing.JButton button_logout;
    private javax.swing.JButton button_update;
    private javax.swing.JButton button_viewall;
    private javax.swing.JComboBox<String> combobox_search;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label_age;
    private javax.swing.JLabel label_enter;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_id_rec;
    private javax.swing.JLabel label_laxis;
    private javax.swing.JLabel label_lcyl;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_opt;
    private javax.swing.JLabel label_paxis;
    private javax.swing.JLabel label_phone;
    private javax.swing.JLabel label_psph;
    private javax.swing.JLabel label_rcyl;
    private javax.swing.JLabel label_rsph;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_vision;
    private javax.swing.JTextField textbox_age;
    private javax.swing.JTextField textbox_laxis;
    private javax.swing.JTextField textbox_lcyl;
    private javax.swing.JTextField textbox_name;
    private javax.swing.JTextField textbox_paxis;
    private javax.swing.JTextField textbox_phone;
    private javax.swing.JTextField textbox_psph;
    private javax.swing.JTextField textbox_rcyl;
    private javax.swing.JTextField textbox_rsph;
    private javax.swing.JTextField textbox_vision;
    private javax.swing.JTextField textfield_search;
    // End of variables declaration//GEN-END:variables
}
