/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
import java.sql.*;
import javax.swing.*;

public class employee_info extends javax.swing.JFrame {

    /**
     * Creates new form employee_info
     */
    set_id ob;
    int permission_emp;
    
    public employee_info(set_id obj) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        label_id_rec.setVisible(false);
        ob = obj;
        permission_emp = ob.employee_perm;
        
        setIconImage(new ImageIcon(".\\icons\\Icon.png").getImage());
    }
    
    ResultSet rs;
    String query;
    String id, name, phone, address, desig, keyword, search;
    
    String setkeyword()
    {
        String choice = combobox_search.getSelectedItem().toString();
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = con.createStatement();
            
            try {
                if (choice.compareTo("ID") == 0)
                query = "SELECT employee_id from employee_information WHERE employee_id = '" + textfield_search.getText() + "'";
                
                if(choice.compareTo("Name") == 0)
                    query = "SELECT employee_id from employee_information WHERE employee_name = '" + textfield_search.getText() + "'";
                
                rs = stm.executeQuery(query);
            }
            catch (SQLException sqlExp) {
                String msg = "'" + choice + "' IS NOT INCLUDED IN THE DATABASE";
                JOptionPane.showMessageDialog(null, msg);
            }
            
            if(rs.next()) {
                keyword = rs.getString("employee_id");
                
                con.close();
            }
        }
        catch (SQLException sqlExp) {
            JOptionPane.showMessageDialog(null, sqlExp);
        }
        
        return keyword;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        button_goback = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        button_viewall = new javax.swing.JButton();
        label_enter = new javax.swing.JLabel();
        textfield_search = new javax.swing.JTextField();
        button_search = new javax.swing.JButton();
        label_name = new javax.swing.JLabel();
        label_phone = new javax.swing.JLabel();
        label_address = new javax.swing.JLabel();
        label_desig = new javax.swing.JLabel();
        button_update = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        textbox_name = new javax.swing.JTextField();
        textbox_phone = new javax.swing.JTextField();
        textbox_address = new javax.swing.JTextField();
        textbox_desig = new javax.swing.JTextField();
        button_permissions = new javax.swing.JButton();
        label_id = new javax.swing.JLabel();
        label_id_rec = new javax.swing.JLabel();
        combobox_search = new javax.swing.JComboBox<>();
        button_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(909, 626));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label_title.setFont(new java.awt.Font("Cinzel Black", 1, 16)); // NOI18N
        label_title.setForeground(new java.awt.Color(0, 0, 0));
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("MUJNABIN OPTIC'S");
        label_title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_title.setAlignmentY(0.0F);

        button_goback.setBackground(new java.awt.Color(0, 204, 204));
        button_goback.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        button_goback.setText("GO BACK");
        button_goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_gobackActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        button_viewall.setBackground(new java.awt.Color(0, 0, 153));
        button_viewall.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_viewall.setText("VIEW ALL");
        button_viewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_viewallActionPerformed(evt);
            }
        });

        label_enter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_enter.setForeground(new java.awt.Color(0, 0, 0));
        label_enter.setText("ENTER:");

        textfield_search.setBackground(new java.awt.Color(255, 255, 255));
        textfield_search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_search.setForeground(new java.awt.Color(0, 0, 0));

        button_search.setBackground(new java.awt.Color(0, 0, 153));
        button_search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_search.setText("SEARCH");
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });

        label_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_name.setForeground(new java.awt.Color(0, 0, 153));
        label_name.setText("NAME:");

        label_phone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_phone.setForeground(new java.awt.Color(0, 0, 153));
        label_phone.setText("PHONE NUMBER:");

        label_address.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_address.setForeground(new java.awt.Color(0, 0, 153));
        label_address.setText("ADDRESS:");

        label_desig.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_desig.setForeground(new java.awt.Color(0, 0, 153));
        label_desig.setText("DESIGNATION:");

        button_update.setBackground(new java.awt.Color(51, 0, 153));
        button_update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_update.setText("UPDATE INFORMATION");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        button_delete.setBackground(new java.awt.Color(51, 0, 153));
        button_delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_delete.setText("REMOVE EMPLOYEE");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        textbox_name.setBackground(new java.awt.Color(255, 255, 255));
        textbox_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_name.setForeground(new java.awt.Color(0, 0, 0));

        textbox_phone.setBackground(new java.awt.Color(255, 255, 255));
        textbox_phone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_phone.setForeground(new java.awt.Color(0, 0, 0));

        textbox_address.setBackground(new java.awt.Color(255, 255, 255));
        textbox_address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_address.setForeground(new java.awt.Color(0, 0, 0));

        textbox_desig.setBackground(new java.awt.Color(255, 255, 255));
        textbox_desig.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textbox_desig.setForeground(new java.awt.Color(0, 0, 0));

        button_permissions.setBackground(new java.awt.Color(51, 0, 153));
        button_permissions.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_permissions.setText("VIEW / CHANGE EMPLOYEE PERMISSIONS");
        button_permissions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_permissionsActionPerformed(evt);
            }
        });

        label_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_id.setForeground(new java.awt.Color(0, 0, 153));
        label_id.setText("ID:");

        label_id_rec.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        label_id_rec.setForeground(new java.awt.Color(0, 0, 0));
        label_id_rec.setText("ID");

        combobox_search.setBackground(new java.awt.Color(255, 255, 255));
        combobox_search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combobox_search.setForeground(new java.awt.Color(0, 0, 0));
        combobox_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(button_viewall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(107, 107, 107))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_name)
                            .addComponent(label_phone)
                            .addComponent(label_desig)
                            .addComponent(label_address)
                            .addComponent(label_enter))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textfield_search, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(combobox_search, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(button_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textbox_address)
                                    .addComponent(textbox_name)
                                    .addComponent(textbox_phone)
                                    .addComponent(textbox_desig))
                                .addGap(66, 66, 66))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label_id_rec)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(button_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(302, 302, 302)
                        .addComponent(button_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(54, 54, 54))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(button_permissions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(284, 284, 284))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_id)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_viewall)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_search)
                    .addComponent(label_enter)
                    .addComponent(combobox_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id)
                    .addComponent(label_id_rec))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name)
                    .addComponent(textbox_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_phone)
                    .addComponent(textbox_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_address)
                    .addComponent(textbox_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textbox_desig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_desig))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_delete)
                    .addComponent(button_update))
                .addGap(37, 37, 37)
                .addComponent(button_permissions)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        button_logout.setBackground(new java.awt.Color(51, 0, 153));
        button_logout.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        button_logout.setText("LOG OUT");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button_goback)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(348, 348, 348)
                                .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(184, 184, 184)
                        .addComponent(button_logout)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_goback)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_logout)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_permissionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_permissionsActionPerformed
        // TODO add your handling code here:
        search = setkeyword();
        new access_permission(null, true, search, 2).show();   
    }//GEN-LAST:event_button_permissionsActionPerformed

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        // TODO add your handling code here:
        dispose();
        
        login_main obj = new login_main();
        obj.show();
    }//GEN-LAST:event_button_logoutActionPerformed

    private void button_viewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_viewallActionPerformed
        // TODO add your handling code here:
        dispose();
        
        viewer_employee obj = new viewer_employee(ob);
        obj.show();                
    }//GEN-LAST:event_button_viewallActionPerformed

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = con.createStatement();
            search = setkeyword();
            
            query = "SELECT * from employee_information WHERE employee_id = '" + search + "'";
            rs = stm.executeQuery(query);
            
            if (rs.next()){
                id = rs.getString("employee_id");
                name = rs.getString("employee_name");
                phone = rs.getString("employee_phone_num");
                address = rs.getString("employee_address");
                desig = rs.getString("designation");
                
                label_id_rec.setText(id);
                label_id_rec.setVisible(true);
                textbox_name.setText(name);
                textbox_phone.setText(phone);
                textbox_address.setText(address);
                textbox_desig.setText(desig);
            }
            
            con.close();
            
        }
        catch (SQLException sqlExp) {
            JOptionPane.showMessageDialog(null, sqlExp);
        }
    }//GEN-LAST:event_button_searchActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:
        try {
            name = textbox_name.getText();
            phone = textbox_phone.getText();
            address = textbox_address.getText();
            desig = textbox_desig.getText();
            search = setkeyword();
            
            if (desig.equals("") || name.equals(""))
                JOptionPane.showMessageDialog(null, "NAME/DESIGNATION CANNOT BE EMPTY");
            
            else
            {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
                Statement stm = con.createStatement();
                stm.execute("SET FOREIGN_KEY_CHECKS=0");
            
                query = "UPDATE `employee_information` SET `employee_name` = '" + name + "',`employee_phone_num` = '" + phone + "',`employee_address` = '" + address + "',`designation`= '" + desig + "' WHERE employee_id = '" + search + "'";
                stm.executeUpdate(query);
            
                stm.execute("SET FOREIGN_KEY_CHECKS=1");            
                con.close();
            
                JOptionPane.showMessageDialog(null, "CHANGES SAVED");
            }
        }
        catch (SQLException sqlExp) {
            JOptionPane.showMessageDialog(null, sqlExp);
        }
    }//GEN-LAST:event_button_updateActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:
        int delcon = JOptionPane.showConfirmDialog(null,"ARE YOU SURE?"); 
        
        if(delcon == JOptionPane.YES_OPTION){
            try{
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
                Statement stm = con.createStatement();
                stm.execute("SET FOREIGN_KEY_CHECKS=0");
                search = setkeyword();

                query = "DELETE FROM `employee_information` WHERE employee_id = '" + search + "'";
                stm.executeUpdate(query);

                query = "DELETE FROM `employee_permissions` WHERE employee_id = '" + search + "'";
                stm.executeUpdate(query);

                query = "DELETE FROM `login_info` WHERE employee_id = '" + search + "'";
                stm.executeUpdate(query);

                query = "UPDATE sales_records SET employee_id = '' WHERE employee_id = '" + search + "'";
                stm.executeUpdate(query);

                stm.execute("SET FOREIGN_KEY_CHECKS=1");            
                con.close();

                JOptionPane.showMessageDialog(null, "EMPLOYEE REMOVED FROM STORE DATABASE");

                employee_info main = new employee_info(ob);
                main.setVisible(true);
                this.dispose();
            }
            catch (SQLException sqlExp) {
                JOptionPane.showMessageDialog(null, sqlExp);
            }
        }
        
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_gobackActionPerformed
        // TODO add your handling code here:
        dispose();

        homepage ob_home = new homepage(ob);
        ob_home.show();
        
    }//GEN-LAST:event_button_gobackActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_goback;
    private javax.swing.JButton button_logout;
    private javax.swing.JButton button_permissions;
    private javax.swing.JButton button_search;
    private javax.swing.JButton button_update;
    private javax.swing.JButton button_viewall;
    private javax.swing.JComboBox<String> combobox_search;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_desig;
    private javax.swing.JLabel label_enter;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_id_rec;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_phone;
    private javax.swing.JLabel label_title;
    private javax.swing.JTextField textbox_address;
    private javax.swing.JTextField textbox_desig;
    private javax.swing.JTextField textbox_name;
    private javax.swing.JTextField textbox_phone;
    private javax.swing.JTextField textfield_search;
    // End of variables declaration//GEN-END:variables
}
