
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class homepage extends javax.swing.JFrame {
    /**
     * Creates new form homepage
     */
    int permission_appointment;
    int permission_emp;
    int permission_client;
    int permission_appoint;
    int permission_product, permission_supplies, permission_sales, permission_orders;
    set_id ob;
    
    public homepage(set_id obj) {
        initComponents();
        ob = obj;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        permission_appointment = ob.appointment_perm;
        permission_client = ob.client_perm;
        permission_emp = ob.employee_perm;
        permission_appoint = ob.appointment_perm;
        permission_product = ob.product_perm;
        permission_supplies = ob.supplies_perm;
        permission_sales = ob.sales_perm;
        permission_orders = ob.orders_perm;
        
        setIconImage(new ImageIcon(".\\icons\\Icon.png").getImage());        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        button_cat = new javax.swing.JButton();
        button_sales = new javax.swing.JButton();
        button_appointments = new javax.swing.JButton();
        button_logout = new javax.swing.JButton();
        button_emp = new javax.swing.JButton();
        button_clients = new javax.swing.JButton();
        label_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        button_cat.setBackground(new java.awt.Color(0, 0, 102));
        button_cat.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        button_cat.setText("CATALOGUE");
        button_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_catActionPerformed(evt);
            }
        });

        button_sales.setBackground(new java.awt.Color(0, 0, 102));
        button_sales.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        button_sales.setText("SALES");
        button_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_salesActionPerformed(evt);
            }
        });

        button_appointments.setBackground(new java.awt.Color(0, 0, 102));
        button_appointments.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        button_appointments.setText("APPOINTMENTS");
        button_appointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_appointmentsActionPerformed(evt);
            }
        });

        button_logout.setBackground(new java.awt.Color(51, 0, 153));
        button_logout.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        button_logout.setText("LOG OUT");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        button_emp.setBackground(new java.awt.Color(51, 0, 102));
        button_emp.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        button_emp.setForeground(new java.awt.Color(255, 255, 255));
        button_emp.setText("EMPLOYEES");
        button_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_empActionPerformed(evt);
            }
        });

        button_clients.setBackground(new java.awt.Color(51, 0, 102));
        button_clients.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        button_clients.setForeground(new java.awt.Color(255, 255, 255));
        button_clients.setText("CLIENTS");
        button_clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_appointments, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addComponent(button_sales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_cat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(206, 206, 206))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_logout))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button_clients, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_logout)
                .addGap(49, 49, 49)
                .addComponent(button_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_appointments, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_clients, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        label_title.setFont(new java.awt.Font("Cinzel Black", 1, 16)); // NOI18N
        label_title.setForeground(new java.awt.Color(0, 0, 0));
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("MUJNABIN OPTIC'S");
        label_title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_title.setAlignmentY(0.0F);
        label_title.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(191, 191, 191))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_title)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_catActionPerformed
        // TODO add your handling code here:
        if (permission_emp == 1 || permission_product == 1 || permission_supplies == 1)
        {
            dispose();
            
            catalogue obj = new catalogue(ob);
            obj.show();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "YOU DO NOT HAVE ACCESS");
        }
        
    }//GEN-LAST:event_button_catActionPerformed

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        // TODO add your handling code here:
        dispose();
        
        login_main obj = new login_main();
        obj.show();
    }//GEN-LAST:event_button_logoutActionPerformed

    private void button_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_empActionPerformed
        // TODO add your handling code here:
        if (permission_emp == 1)
        {
            dispose();
        
            employee_info obj = new employee_info(ob);
            obj.show();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "YOU DO NOT HAVE ACCESS");
        }
        
    }//GEN-LAST:event_button_empActionPerformed

    private void button_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_salesActionPerformed
        // TODO add your handling code here:
        if (permission_emp == 1 || permission_sales == 1 || permission_orders == 1)
        {
            dispose();
            
            sales obj = new sales(ob);
            obj.show();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "YOU DO NOT HAVE ACCESS");
        }
        
    }//GEN-LAST:event_button_salesActionPerformed

    private void button_clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clientsActionPerformed
        // TODO add your handling code here:
        if (permission_client == 1)
        {
            dispose();
        
            client_info obj = new client_info(ob);
            obj.show();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "YOU DO NOT HAVE ACCESS");
        }
    }//GEN-LAST:event_button_clientsActionPerformed

    private void button_appointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_appointmentsActionPerformed
        // TODO add your handling code here:
        if (permission_appoint == 1)
        {
            dispose();
        
            appoint_menu obj = new appoint_menu(ob);
            obj.show();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "YOU DO NOT HAVE ACCESS");
        }
    }//GEN-LAST:event_button_appointmentsActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_appointments;
    private javax.swing.JButton button_cat;
    private javax.swing.JButton button_clients;
    private javax.swing.JButton button_emp;
    private javax.swing.JButton button_logout;
    private javax.swing.JButton button_sales;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_title;
    // End of variables declaration//GEN-END:variables
}
