
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class new_product extends javax.swing.JDialog {

    /**
     * Creates new form new_product
     */
    String quantity;
    
    public new_product(java.awt.Frame parent, boolean modal, String prod_id, String q) {
        super(parent, modal);
        initComponents();
        
        label_id_rec.setText(prod_id);
        quantity = q;
        
        setIconImage(new ImageIcon(".\\icons\\Icon.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_permission_title = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        button_ok = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        label_brand = new javax.swing.JLabel();
        textfield_brand = new javax.swing.JTextField();
        label_id_rec = new javax.swing.JLabel();
        label_shape = new javax.swing.JLabel();
        textfield_shape = new javax.swing.JTextField();
        label_design = new javax.swing.JLabel();
        textfield_design = new javax.swing.JTextField();
        label_material = new javax.swing.JLabel();
        textfield_material = new javax.swing.JTextField();
        label_selling_price = new javax.swing.JLabel();
        textfield_selling_price = new javax.swing.JTextField();
        label_cost_price = new javax.swing.JLabel();
        textfield_cost_price = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label_permission_title.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        label_permission_title.setForeground(new java.awt.Color(0, 0, 0));
        label_permission_title.setText("NEW PRODUCT");

        label_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_id.setForeground(new java.awt.Color(0, 0, 153));
        label_id.setText("PRODUCT ID:");

        button_ok.setBackground(new java.awt.Color(0, 0, 153));
        button_ok.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_ok.setText("OK");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        button_cancel.setBackground(new java.awt.Color(0, 0, 153));
        button_cancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_cancel.setText("CANCEL");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        label_brand.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_brand.setForeground(new java.awt.Color(0, 0, 153));
        label_brand.setText("BRAND:");

        textfield_brand.setBackground(new java.awt.Color(255, 255, 255));
        textfield_brand.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_brand.setForeground(new java.awt.Color(0, 0, 0));

        label_id_rec.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        label_id_rec.setForeground(new java.awt.Color(0, 0, 0));
        label_id_rec.setText("ID");

        label_shape.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_shape.setForeground(new java.awt.Color(0, 0, 153));
        label_shape.setText("SHAPE:");

        textfield_shape.setBackground(new java.awt.Color(255, 255, 255));
        textfield_shape.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_shape.setForeground(new java.awt.Color(0, 0, 0));

        label_design.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_design.setForeground(new java.awt.Color(0, 0, 153));
        label_design.setText("DESIGN:");

        textfield_design.setBackground(new java.awt.Color(255, 255, 255));
        textfield_design.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_design.setForeground(new java.awt.Color(0, 0, 0));

        label_material.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_material.setForeground(new java.awt.Color(0, 0, 153));
        label_material.setText("MATERIAL:");

        textfield_material.setBackground(new java.awt.Color(255, 255, 255));
        textfield_material.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_material.setForeground(new java.awt.Color(0, 0, 0));

        label_selling_price.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_selling_price.setForeground(new java.awt.Color(0, 0, 153));
        label_selling_price.setText("SELLING PRICE:");

        textfield_selling_price.setBackground(new java.awt.Color(255, 255, 255));
        textfield_selling_price.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_selling_price.setForeground(new java.awt.Color(0, 0, 0));

        label_cost_price.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_cost_price.setForeground(new java.awt.Color(0, 0, 153));
        label_cost_price.setText("COST PRICE:");

        textfield_cost_price.setBackground(new java.awt.Color(255, 255, 255));
        textfield_cost_price.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_cost_price.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_shape)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textfield_shape, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_design)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textfield_design, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_material)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textfield_material, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_brand)
                            .addComponent(label_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_id_rec)
                            .addComponent(textfield_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label_permission_title)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_selling_price)
                            .addComponent(label_cost_price))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_cost_price, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_selling_price, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_permission_title)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id)
                    .addComponent(label_id_rec))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_brand)
                    .addComponent(textfield_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_shape)
                    .addComponent(textfield_shape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_design)
                    .addComponent(textfield_design, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_material)
                    .addComponent(textfield_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cost_price)
                    .addComponent(textfield_cost_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_selling_price)
                    .addComponent(textfield_selling_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_ok)
                    .addComponent(button_cancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        // TODO add your handling code here:        
        try {
            String id = label_id_rec.getText();
            String brand = textfield_brand.getText();
            String shape = textfield_shape.getText();
            String design = textfield_design.getText();
            String material = textfield_material.getText();
            String cost_price = textfield_cost_price.getText();
            String selling_price = textfield_selling_price.getText();
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = null;
                                    
            if (textfield_cost_price.getText().length()==0 || textfield_brand.getText().length()==0) {
                JOptionPane.showMessageDialog(null, "NECESSARY INFORMATION MISSING");
            }
            
            else {
                if (textfield_selling_price.getText().isBlank()) {
                    selling_price = String.valueOf(0);
                }

                
                String acc_emp = "INSERT INTO `product_info`(`product_id`, `brand`, `shape`, `design`, `material`, `quantity`, `unit_cost_price`, `unit_selling_price`) VALUES ('" + id + "', '" + brand + "', '" + shape + "', '" + design + "', '" + material + "', " + quantity + ", " + cost_price + ", " + selling_price + ")";
            
                stm = con.createStatement();
            
                stm.executeUpdate(acc_emp);
                
                JOptionPane.showMessageDialog(null, "PRODUCT ADDED TO DATABASE");
            
                con.close();
                    
                dispose();
            }
        }
            
        catch(SQLException sqlExp) {
            JOptionPane.showMessageDialog(null,sqlExp);
        }
        catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(null,"SIGNUP FAILED");
        }
    }//GEN-LAST:event_button_okActionPerformed

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_button_cancelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_ok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_brand;
    private javax.swing.JLabel label_cost_price;
    private javax.swing.JLabel label_design;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_id_rec;
    private javax.swing.JLabel label_material;
    private javax.swing.JLabel label_permission_title;
    private javax.swing.JLabel label_selling_price;
    private javax.swing.JLabel label_shape;
    private javax.swing.JTextField textfield_brand;
    private javax.swing.JTextField textfield_cost_price;
    private javax.swing.JTextField textfield_design;
    private javax.swing.JTextField textfield_material;
    private javax.swing.JTextField textfield_selling_price;
    private javax.swing.JTextField textfield_shape;
    // End of variables declaration//GEN-END:variables
}
