
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class suppliers extends javax.swing.JFrame {

    /**
     * Creates new form suppliers
     */
    set_id ob;
    int permission_emp;
    int permission_supplies;
    String setID;
    
    public suppliers(set_id obj) {
        initComponents();
        ob = obj;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        permission_emp = ob.employee_perm;
        permission_supplies = ob.supplies_perm;
        
        label_id_gen.setVisible(false);
        label_total_supplies.setVisible(false);
        label_total_supplies_value.setVisible(false);
        
        setIconImage(new ImageIcon(".\\icons\\Icon.png").getImage());
    }
    
    ResultSet rs;
    String query;
    String id, name, phone, address, search;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        button_goback = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        button_viewall = new javax.swing.JButton();
        textfield_search = new javax.swing.JTextField();
        button_search = new javax.swing.JButton();
        label_id = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        label_phone = new javax.swing.JLabel();
        label_address = new javax.swing.JLabel();
        textfield_name = new javax.swing.JTextField();
        textfield_phone = new javax.swing.JTextField();
        textfield_address = new javax.swing.JTextField();
        button_add = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        label_search = new javax.swing.JLabel();
        label_id_gen = new javax.swing.JLabel();
        label_total_supplies = new javax.swing.JLabel();
        label_total_supplies_value = new javax.swing.JLabel();
        button_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(909, 626));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label_title.setFont(new java.awt.Font("Cinzel Black", 1, 16)); // NOI18N
        label_title.setForeground(new java.awt.Color(0, 0, 0));
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("MUJNABIN OPTIC'S");
        label_title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_title.setAlignmentY(0.0F);

        button_goback.setBackground(new java.awt.Color(0, 204, 204));
        button_goback.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        button_goback.setText("GO BACK");
        button_goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_gobackActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 153));

        button_viewall.setBackground(new java.awt.Color(0, 0, 153));
        button_viewall.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_viewall.setText("VIEW ALL");
        button_viewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_viewallActionPerformed(evt);
            }
        });

        textfield_search.setBackground(new java.awt.Color(255, 255, 255));
        textfield_search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_search.setForeground(new java.awt.Color(0, 0, 0));

        button_search.setBackground(new java.awt.Color(0, 0, 153));
        button_search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_search.setText("SEARCH");
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });

        label_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_id.setForeground(new java.awt.Color(0, 0, 153));
        label_id.setText("SUPPLIER ID:");

        label_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_name.setForeground(new java.awt.Color(0, 0, 153));
        label_name.setText("NAME:");

        label_phone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_phone.setForeground(new java.awt.Color(0, 0, 153));
        label_phone.setText("PHONE NUMBER:");

        label_address.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_address.setForeground(new java.awt.Color(0, 0, 153));
        label_address.setText("ADDRESS:");

        textfield_name.setBackground(new java.awt.Color(255, 255, 255));
        textfield_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_name.setForeground(new java.awt.Color(0, 0, 0));

        textfield_phone.setBackground(new java.awt.Color(255, 255, 255));
        textfield_phone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_phone.setForeground(new java.awt.Color(0, 0, 0));

        textfield_address.setBackground(new java.awt.Color(255, 255, 255));
        textfield_address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textfield_address.setForeground(new java.awt.Color(0, 0, 0));

        button_add.setBackground(new java.awt.Color(51, 0, 153));
        button_add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_add.setText("ADD NEW SUPPLIER");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        button_delete.setBackground(new java.awt.Color(51, 0, 153));
        button_delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_delete.setText("REMOVE SUPPLIER");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_update.setBackground(new java.awt.Color(51, 0, 153));
        button_update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_update.setText("UPDATE INFORMATION");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        label_search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_search.setForeground(new java.awt.Color(255, 255, 255));
        label_search.setText("ENTER SUPPLIER NAME:");

        label_id_gen.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        label_id_gen.setForeground(new java.awt.Color(0, 0, 0));
        label_id_gen.setText("ID");

        label_total_supplies.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_total_supplies.setForeground(new java.awt.Color(0, 0, 0));
        label_total_supplies.setText("TOTAL SUPPLIES:");

        label_total_supplies_value.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        label_total_supplies_value.setForeground(new java.awt.Color(0, 0, 0));
        label_total_supplies_value.setText("VALUE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(label_search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textfield_search, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(button_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(82, 82, 82)
                        .addComponent(button_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(107, 107, 107)
                        .addComponent(button_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_id)
                                    .addComponent(label_name)
                                    .addComponent(label_address))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfield_address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_id_gen)
                                    .addComponent(textfield_name, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label_phone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfield_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_total_supplies)
                                .addGap(18, 18, 18)
                                .addComponent(label_total_supplies_value, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(button_viewall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(169, 169, 169))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(button_viewall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_search)
                    .addComponent(label_search))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id)
                    .addComponent(label_id_gen))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name)
                    .addComponent(textfield_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_total_supplies)
                        .addComponent(label_total_supplies_value))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_phone)
                        .addComponent(textfield_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_address))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_add)
                    .addComponent(button_delete)
                    .addComponent(button_update))
                .addGap(107, 107, 107))
        );

        button_logout.setBackground(new java.awt.Color(51, 0, 153));
        button_logout.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        button_logout.setText("LOG OUT");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_goback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_logout)
                        .addGap(22, 22, 22))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(268, 268, 268))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_title)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_goback)
                    .addComponent(button_logout))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        // TODO add your handling code here:
        dispose();
        
        login_main obj = new login_main();
        obj.show();
    }//GEN-LAST:event_button_logoutActionPerformed

    private void button_gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_gobackActionPerformed
        // TODO add your handling code here:
        if (permission_emp == 1 || permission_supplies == 1)
        {
            dispose();
        
            cat_placed_orders obj = new cat_placed_orders(ob);
            obj.show();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "YOU DO NOT HAVE ACCESS");
        }
        
    }//GEN-LAST:event_button_gobackActionPerformed

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = con.createStatement();
            search = textfield_search.getText();
            
            if(search.contains("'")){                
                search = search.replaceAll("'", "''");
            }

            
            query = "SELECT * from supplier_info WHERE supplier_name = '" + search + "'";
            rs = stm.executeQuery(query);
            
            if (rs.next()){
                id = rs.getString("supplier_id");
                name = rs.getString("supplier_name");
                phone = rs.getString("supplier_phone_num");
                address = rs.getString("supplier_address");
                
                label_id_gen.setText(id);
                label_id_gen.setVisible(true);
                textfield_name.setText(name);
                textfield_phone.setText(phone);
                textfield_address.setText(address);
                
                query = "SELECT COUNT(supplier_id) from supplies_info WHERE supplier_id = '" + id + "'";
                rs = stm.executeQuery(query);
                
                if (rs.next()){
                    label_total_supplies_value.setText(rs.getString(1));
                    label_total_supplies.setVisible(true);
                    label_total_supplies_value.setVisible(true);
                }
            }
            
            else
                JOptionPane.showMessageDialog(null, "SUPPLIER NOT INCLUDED IN THE DATABASE");
            
            con.close();
            
        }
        catch (SQLException sqlExp) {
            JOptionPane.showMessageDialog(null, sqlExp);
        }
    }//GEN-LAST:event_button_searchActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:
        try {
            name = textfield_name.getText();
            phone = textfield_phone.getText();
            address = textfield_address.getText();
            search = textfield_search.getText();
            
            if(name.contains("'")){                
                name = name.replaceAll("'", "''");
            }
            
            if(search.contains("'")){                
                search = search.replaceAll("'", "''");
            }
            
            if (phone.equals("") || name.equals(""))
                JOptionPane.showMessageDialog(null, "NAME/PHONE NUMBER CANNOT BE EMPTY");
            
            else
            {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
                Statement stm = con.createStatement();
                stm.execute("SET FOREIGN_KEY_CHECKS=0");
            
                query = "UPDATE `supplier_info` SET `supplier_name` = '" + name + "',`supplier_phone_num` = '" + phone + "',`supplier_address` = '" + address + "' WHERE supplier_name = '" + search + "'";
                stm.executeUpdate(query);
            
                stm.execute("SET FOREIGN_KEY_CHECKS=1");            
                con.close();
            
                JOptionPane.showMessageDialog(null, "CHANGES SAVED");
            }
        }
        catch (SQLException sqlExp) {
            JOptionPane.showMessageDialog(null, sqlExp);
        }
    }//GEN-LAST:event_button_updateActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:
        int delcon = JOptionPane.showConfirmDialog(null,"ARE YOU SURE?"); 
        
        if(delcon == JOptionPane.YES_OPTION){
            try{
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
                Statement stm = con.createStatement();
                stm.execute("SET FOREIGN_KEY_CHECKS=0");
                search = textfield_search.getText();
                
                if(search.contains("'")){                
                    search = search.replaceAll("'", "''");
                }


                query = "DELETE FROM supplier_info WHERE supplier_name= '" + search + "'";
                stm.executeUpdate(query);

                stm.execute("SET FOREIGN_KEY_CHECKS=1");            
                con.close();

                JOptionPane.showMessageDialog(null, "SUPPLIER REMOVED FROM STORE DATABASE");

                dispose();
                suppliers main = new suppliers(ob);
                main.setVisible(true);
            }
            catch (SQLException sqlExp) {
                JOptionPane.showMessageDialog(null, sqlExp);
            }
        }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        // TODO add your handling code here:
        settingID();
        try {
            name = textfield_name.getText();
            phone = textfield_phone.getText();
            address = textfield_address.getText();
            
            if(name.contains("'")){                
                name = name.replaceAll("'", "''");
            }

            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = null;
                                    
            if (textfield_name.getText().length()==0 || textfield_phone.getText().length()==0) {
                JOptionPane.showMessageDialog(null, "NAME/PHONE CANNOT BE EMPTY");
            }
            
            else if (supplier_check() == true){
                JOptionPane.showMessageDialog(null,"SUPPLIER ALREADY EXISTS");
            }
            
            else {
                String acc_emp = "INSERT INTO `supplier_info`(`supplier_id`, `supplier_name`, `supplier_phone_num`, `supplier_address`) VALUES ('" + setID + "', '" + name + "', '" + phone + "', '" + address + "')";
            
                stm = con.createStatement();
            
                stm.executeUpdate(acc_emp);
                
                label_id_gen.setText(setID);            
                String msg = "SUPPLIER ADDED TO DATABASE\nSUPPLIER ID: " + setID;
                JOptionPane.showMessageDialog(null,msg);
                label_id_gen.setVisible(true);
            
                con.close();
                
                suppliers main = new suppliers(ob);
                main.setVisible(true);
                this.dispose();
            }
        }
            
        catch(SQLException sqlExp) {
            JOptionPane.showMessageDialog(null,"DATABASE CONNECTION FAILED");
        }
        catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(null,"SIGNUP FAILED");
        } 
    }//GEN-LAST:event_button_addActionPerformed

    private void button_viewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_viewallActionPerformed
        // TODO add your handling code here:
        if (permission_emp == 1)
        {
            dispose();

            viewer_supplier obj = new viewer_supplier(ob);
            obj.show();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "YOU DO NOT HAVE ACCESS");
        }
    }//GEN-LAST:event_button_viewallActionPerformed

    boolean supplier_check()
    {
        int x = 0;
        try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
                PreparedStatement stm;
                ResultSet rs;

                String name_given = textfield_name.getText();
                String phone_given = textfield_phone.getText();

                stm = con.prepareStatement("Select supplier_name, supplier_phone_num from supplier_info where supplier_name = ? and supplier_phone_num = ?");

                stm.setString(1, name_given);
                stm.setString(2, phone_given);
                rs = stm.executeQuery();

                if (rs.next()) {
                    con.close();    
                    x = 1;                    
                }
                
                else {
                    x = 0;
                }
            
            }
        catch (SQLException sqlExp) {
            JOptionPane.showMessageDialog(null,"DATABASE CONNECTION FAILED");
        }
        
        if (x == 1) {
            return true;                    
        } 
        else {
            return false;
        }
    }
    
    void settingID()
    {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = (Statement) con.createStatement();
            ResultSet rs;
                 
            rs = stm.executeQuery("SELECT MAX(`supplier_id`) FROM `supplier_info`");
            rs.next();
            
            String set_id_str;
            set_id_str = rs.getString(1);
                
            int new_id = Integer.parseInt(set_id_str) + 1;
            setID = String.valueOf(new_id);
            
        }
        catch(SQLException sqlExp) {
            JOptionPane.showMessageDialog(null,"DATABASE CONNECTION FAILED");
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_goback;
    private javax.swing.JButton button_logout;
    private javax.swing.JButton button_search;
    private javax.swing.JButton button_update;
    private javax.swing.JButton button_viewall;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_id_gen;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_phone;
    private javax.swing.JLabel label_search;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_total_supplies;
    private javax.swing.JLabel label_total_supplies_value;
    private javax.swing.JTextField textfield_address;
    private javax.swing.JTextField textfield_name;
    private javax.swing.JTextField textfield_phone;
    private javax.swing.JTextField textfield_search;
    // End of variables declaration//GEN-END:variables
}
