import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class viewer_client extends javax.swing.JFrame {

    /**
     * Creates new form viewer_client
     */
    set_id ob;
    int permission_emp;
    int permission_client;
    int app = 0;
    appoint_menu appoint;
    
    public viewer_client(set_id obj) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        client_info();
        
        ob = obj;
        permission_emp = ob.employee_perm;
        permission_client = ob.client_perm;
        
        setIconImage(new ImageIcon(".\\icons\\Icon.png").getImage());
    }
    
    public viewer_client(set_id obj, int x, appoint_menu a) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        client_info();
        app = x;
        appoint = a;
        
        ob = obj;
        permission_emp = ob.employee_perm;
        permission_client = ob.client_perm;
        
        setIconImage(new ImageIcon(".\\icons\\Icon.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        button_goback = new javax.swing.JButton();
        label_emp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_client = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label_title.setFont(new java.awt.Font("Cinzel Black", 1, 16)); // NOI18N
        label_title.setForeground(new java.awt.Color(0, 0, 0));
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("MUJNABIN OPTIC'S");
        label_title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_title.setAlignmentY(0.0F);

        button_goback.setBackground(new java.awt.Color(0, 204, 204));
        button_goback.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        button_goback.setText("GO BACK");
        button_goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_gobackActionPerformed(evt);
            }
        });

        label_emp.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        label_emp.setForeground(new java.awt.Color(0, 0, 0));
        label_emp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_emp.setText("CLIENT INFORMATION");
        label_emp.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_emp.setAlignmentY(0.0F);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table_client.setBackground(new java.awt.Color(102, 255, 255));
        table_client.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        table_client.setForeground(new java.awt.Color(0, 0, 0));
        table_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CLIENT ID", "NAME", "PHONE NUMBER", "AGE", "VISION", "RIGHT SPH", "RIGHT CYL", "POWER AXIS", "POWER SPH", "LEFT CYL", "LEFT AXIS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_clientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_client);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_goback)
                .addGap(241, 241, 241)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_emp, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(317, 317, 317))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(button_goback)))
                .addGap(45, 45, 45)
                .addComponent(label_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_gobackActionPerformed
        // TODO add your handling code here:
        if (app == 1){            
            appoint.show();
            dispose();
        }
        else{
            if ((permission_emp == 1 || permission_client == 1))
            {
                dispose();

                client_info obj = new client_info(ob);
                obj.show();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "YOU DO NOT HAVE ACCESS");
            }
        }
        
    }//GEN-LAST:event_button_gobackActionPerformed

    private void table_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_clientMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && app == 1){
            int srow = table_client.getSelectedRow();
            
            String id = table_client.getValueAt(srow, 0).toString();
            
            appoint.client_select(id);
            appoint.show();
            dispose();
        }
    }//GEN-LAST:event_table_clientMouseClicked

    /**
     * @param args the command line arguments
     */
    void client_info()
    {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = con.createStatement();
            ResultSet rs;
            String query;
            
            query = "SELECT * from client_info";
            
            rs = stm.executeQuery(query);
            
            while (rs.next()) {
                String id = rs.getString("client_id");
                String name = rs.getString("client_name");
                String phone = rs.getString("client_phone_num");
                String age = String.valueOf(rs.getInt("age"));
                String vision = rs.getString("vision");
                String rsph = String.valueOf(rs.getDouble("right_sph"));
                String rcyl = String.valueOf(rs.getFloat("right_cyl"));
                String paxis = String.valueOf(rs.getFloat("power_axis"));
                String psph = String.valueOf(rs.getFloat("power_sph"));
                String lcyl = String.valueOf(rs.getFloat("left_cyl"));
                String laxis = String.valueOf(rs.getFloat("left_axis"));
                
                if (age.equals("0"))
                    age = "";
                if (rsph.equals("0.0"))
                    rsph = "";
                if (rcyl.equals("0.0"))
                    rcyl = "";
                if (paxis.equals("0.0"))
                    paxis = "";
                if (psph.equals("0.0"))
                    psph = "";
                if (lcyl.equals("0.0"))
                    lcyl = "";
                if (laxis.equals("0.0"))
                    laxis = "";
                
                
                String[] tbdata = {id, name, phone, age, vision, rsph, rcyl, paxis, psph, lcyl, laxis};
                
                DefaultTableModel tblmod = (DefaultTableModel) table_client.getModel();
                tblmod.addRow(tbdata);
                
            }
            
            con.close();
        }
        catch (SQLException exp) {
            JOptionPane.showMessageDialog(null, exp);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_goback;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_emp;
    private javax.swing.JLabel label_title;
    private javax.swing.JTable table_client;
    // End of variables declaration//GEN-END:variables
}
