
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class viewer_sales extends javax.swing.JFrame {

    /**
     * Creates new form viewer_sales
     */
    set_id ob;
    int permission_emp;
    int permission_sales;
    int mode;
    viewer_client_orders n;
    
    public viewer_sales(set_id obj, int x, String receipt, viewer_client_orders s) {
        initComponents();
        
        ob = obj; 
        permission_emp = ob.employee_perm;
        permission_sales = ob.sales_perm;
        
        sales_info(receipt);
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        mode = x;
        n = s;
        
        setIconImage(new ImageIcon(".\\icons\\Icon.png").getImage());
    }
    
    public viewer_sales(set_id obj, int x, String receipt) {
        initComponents();
        
        ob = obj; 
        permission_emp = ob.employee_perm;
        permission_sales = ob.sales_perm;
        
        sales_info(receipt);
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        mode = x;
        
        setIconImage(new ImageIcon(".\\icons\\Icon.png").getImage());
    }
    
    int total_row;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        button_goback = new javax.swing.JButton();
        label_receipt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_sales = new javax.swing.JTable();
        label_receipt_gen = new javax.swing.JLabel();
        label_emp = new javax.swing.JLabel();
        label_emp_gen = new javax.swing.JLabel();
        label_client = new javax.swing.JLabel();
        label_client_gen = new javax.swing.JLabel();
        label_total = new javax.swing.JLabel();
        label_total_gen = new javax.swing.JLabel();
        label_payment = new javax.swing.JLabel();
        label_payment_gen = new javax.swing.JLabel();
        label_due = new javax.swing.JLabel();
        label_due_gen = new javax.swing.JLabel();
        label_order_date = new javax.swing.JLabel();
        label_order_date_gen = new javax.swing.JLabel();
        label_full_pay = new javax.swing.JLabel();
        combobox_pay_full = new javax.swing.JComboBox<>();
        button_ok = new javax.swing.JButton();
        label_client_name = new javax.swing.JLabel();
        label_client_name_gen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label_title.setFont(new java.awt.Font("Cinzel Black", 1, 16)); // NOI18N
        label_title.setForeground(new java.awt.Color(0, 0, 0));
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("MUJNABIN OPTIC'S");
        label_title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_title.setAlignmentY(0.0F);

        button_goback.setBackground(new java.awt.Color(0, 204, 204));
        button_goback.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        button_goback.setText("GO BACK");
        button_goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_gobackActionPerformed(evt);
            }
        });

        label_receipt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_receipt.setForeground(new java.awt.Color(0, 0, 0));
        label_receipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_receipt.setText("RECEIPT NO.:");
        label_receipt.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_receipt.setAlignmentY(0.0F);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table_sales.setBackground(new java.awt.Color(102, 255, 255));
        table_sales.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        table_sales.setForeground(new java.awt.Color(0, 0, 0));
        table_sales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "BRAND", "LENS TYPE", "LENS MATERIAL", "FRAME LENGTH", "NOSE LENGTH", "QUANTITY", "UNIT PRICE", "TOTAL PRICE", "DELIVERY DATE", "ORDER STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_sales);

        label_receipt_gen.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        label_receipt_gen.setForeground(new java.awt.Color(0, 0, 0));
        label_receipt_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_receipt_gen.setText("RECEIPT NO.:");
        label_receipt_gen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_receipt_gen.setAlignmentY(0.0F);

        label_emp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_emp.setForeground(new java.awt.Color(0, 0, 0));
        label_emp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_emp.setText("EMPLOYEE ID:");
        label_emp.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_emp.setAlignmentY(0.0F);

        label_emp_gen.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        label_emp_gen.setForeground(new java.awt.Color(0, 0, 0));
        label_emp_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_emp_gen.setText("RECEIPT NO.:");
        label_emp_gen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_emp_gen.setAlignmentY(0.0F);

        label_client.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_client.setForeground(new java.awt.Color(0, 0, 0));
        label_client.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_client.setText("CLIENT ID:");
        label_client.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_client.setAlignmentY(0.0F);

        label_client_gen.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        label_client_gen.setForeground(new java.awt.Color(0, 0, 0));
        label_client_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_client_gen.setText("RECEIPT NO.:");
        label_client_gen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_client_gen.setAlignmentY(0.0F);

        label_total.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_total.setForeground(new java.awt.Color(0, 0, 0));
        label_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_total.setText("FINAL TOTAL:");
        label_total.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_total.setAlignmentY(0.0F);

        label_total_gen.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        label_total_gen.setForeground(new java.awt.Color(0, 0, 0));
        label_total_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_total_gen.setText("RECEIPT NO.:");
        label_total_gen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_total_gen.setAlignmentY(0.0F);

        label_payment.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_payment.setForeground(new java.awt.Color(0, 0, 0));
        label_payment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_payment.setText("PAYMENT:");
        label_payment.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_payment.setAlignmentY(0.0F);

        label_payment_gen.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        label_payment_gen.setForeground(new java.awt.Color(0, 0, 0));
        label_payment_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_payment_gen.setText("RECEIPT NO.:");
        label_payment_gen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_payment_gen.setAlignmentY(0.0F);

        label_due.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_due.setForeground(new java.awt.Color(0, 0, 0));
        label_due.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_due.setText("DUE:");
        label_due.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_due.setAlignmentY(0.0F);

        label_due_gen.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        label_due_gen.setForeground(new java.awt.Color(0, 0, 0));
        label_due_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_due_gen.setText("RECEIPT NO.:");
        label_due_gen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_due_gen.setAlignmentY(0.0F);

        label_order_date.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_order_date.setForeground(new java.awt.Color(0, 0, 0));
        label_order_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_order_date.setText("ORDER/PURCHASE DATE:");
        label_order_date.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_order_date.setAlignmentY(0.0F);

        label_order_date_gen.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        label_order_date_gen.setForeground(new java.awt.Color(0, 0, 0));
        label_order_date_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_order_date_gen.setText("RECEIPT NO.:");
        label_order_date_gen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_order_date_gen.setAlignmentY(0.0F);

        label_full_pay.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_full_pay.setForeground(new java.awt.Color(0, 0, 0));
        label_full_pay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_full_pay.setText("PAID IN FULL:");
        label_full_pay.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_full_pay.setAlignmentY(0.0F);

        combobox_pay_full.setBackground(new java.awt.Color(255, 255, 255));
        combobox_pay_full.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combobox_pay_full.setForeground(new java.awt.Color(0, 0, 0));
        combobox_pay_full.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));

        button_ok.setBackground(new java.awt.Color(0, 0, 102));
        button_ok.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_ok.setText("OK");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        label_client_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_client_name.setForeground(new java.awt.Color(0, 0, 0));
        label_client_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_client_name.setText("CLIENT NAME:");
        label_client_name.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_client_name.setAlignmentY(0.0F);

        label_client_name_gen.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        label_client_name_gen.setForeground(new java.awt.Color(0, 0, 0));
        label_client_name_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_client_name_gen.setText("RECEIPT NO.:");
        label_client_name_gen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_client_name_gen.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_goback)
                        .addGap(214, 214, 214)
                        .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                        .addGap(285, 285, 285))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(label_emp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_emp_gen)
                                .addGap(48, 48, 48)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(label_receipt)
                        .addGap(18, 18, 18)
                        .addComponent(label_receipt_gen)
                        .addGap(115, 115, 115)
                        .addComponent(label_client)
                        .addGap(18, 18, 18)
                        .addComponent(label_client_gen)
                        .addGap(82, 82, 82)
                        .addComponent(label_client_name)
                        .addGap(18, 18, 18)
                        .addComponent(label_client_name_gen)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(label_full_pay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_pay_full, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_total_gen)
                        .addGap(64, 64, 64)
                        .addComponent(label_payment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_payment_gen)
                        .addGap(56, 56, 56)
                        .addComponent(label_due)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_due_gen)))
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_order_date)
                        .addGap(18, 18, 18)
                        .addComponent(label_order_date_gen)
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(button_goback)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_client_name)
                        .addComponent(label_client_name_gen))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_receipt)
                        .addComponent(label_receipt_gen)
                        .addComponent(label_client)
                        .addComponent(label_client_gen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_emp)
                    .addComponent(label_emp_gen))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_total)
                    .addComponent(label_total_gen)
                    .addComponent(label_due)
                    .addComponent(label_due_gen)
                    .addComponent(label_payment)
                    .addComponent(label_payment_gen))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_order_date)
                    .addComponent(label_order_date_gen))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_full_pay)
                    .addComponent(combobox_pay_full, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_gobackActionPerformed
        // TODO add your handling code here:
        if ((permission_emp == 1 || permission_sales == 1) && mode == 1)
        {
            dispose();

            sales_records obj = new sales_records(ob);
            obj.show();
        }        
        else if ((permission_emp == 1 || permission_sales == 1) && mode == 2)
        {
            dispose();

            n.show();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "YOU DO NOT HAVE ACCESS");
        }
    }//GEN-LAST:event_button_gobackActionPerformed

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = con.createStatement();
            String query;
            
            stm.execute("SET FOREIGN_KEY_CHECKS=0");

            for(int i = 0; i < total_row; i++){
                query = "UPDATE client_order_specs SET order_status = '" + table_sales.getValueAt(i, 10).toString() + "' WHERE receipt_no = '" + label_receipt_gen.getText() + "' AND product_id = '" + table_sales.getValueAt(i, 0).toString() + "'";
                stm.executeUpdate(query);
            }
                
            query = "UPDATE sales_records SET pay_cleared = '" + combobox_pay_full.getSelectedItem().toString() + "' WHERE receipt_no = '" + label_receipt_gen.getText() + "'";
            stm.executeUpdate(query);
        
            JOptionPane.showMessageDialog(null, "CHANGES SAVED");
            
            stm.execute("SET FOREIGN_KEY_CHECKS=1");
            con.close();
            
        }

        catch (SQLException exp) {
            JOptionPane.showMessageDialog(null, exp);
        }
        
        if ((permission_emp == 1 || permission_sales == 1) && mode == 1)
        {
            dispose();

            sales_records obj = new sales_records(ob);
            obj.show();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "YOU DO NOT HAVE ACCESS");
        }
    }//GEN-LAST:event_button_okActionPerformed

    void sales_info(String receipt)
    {
        total_row = 0;        
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/optical_store_management_system", "root", "");
            Statement stm = con.createStatement();
            ResultSet rs;
            String query;
            
            query = "SELECT client_order_specs.product_id, client_order_specs.quantity, lens_type, lens_material, frame_length, nose_length, order_status, sales_records.client_id, client_name, payment, order_date, delivery_date, employee_id, pay_cleared, brand, unit_selling_price, (client_order_specs.quantity * unit_selling_price) AS 'total_price' FROM client_order_specs, sales_records, product_info, client_info WHERE client_order_specs.receipt_no = sales_records.receipt_no AND client_order_specs.product_id = product_info.product_id AND client_info.client_id = sales_records.client_id AND sales_records.receipt_no = '" + receipt + "'";
            
            rs = stm.executeQuery(query);
            
            while (rs.next()) {
                label_receipt_gen.setText(receipt);
                label_client_gen.setText(rs.getString("client_id"));
                label_client_name_gen.setText(rs.getString("client_name"));
                label_emp_gen.setText(rs.getString("employee_id"));
                label_payment_gen.setText(rs.getString("payment"));
                label_order_date_gen.setText(rs.getString("order_date"));
                combobox_pay_full.setSelectedItem(rs.getString("pay_cleared"));
                
                String product = rs.getString("product_id");
                String brand = rs.getString("brand");
                String lens_type = rs.getString("lens_type");
                String lens_material = rs.getString("lens_material");
                String frame_len = rs.getString("frame_length");
                String nose_len = rs.getString("nose_length");
                String quantity = rs.getString("quantity");
                String unit_price = rs.getString("unit_selling_price");
                String total_price = rs.getString("total_price");
                String order_status = rs.getString("order_status");
                String del_date = rs.getString("delivery_date");
                
                if (del_date == null || del_date.equals("0000-00-00"))
                    del_date = "NO DELIVERY";

                
                String[] tbdata = {product, brand, lens_type, lens_material, frame_len, nose_len, quantity, unit_price, total_price, del_date, order_status};
                
                DefaultTableModel tblmod = (DefaultTableModel) table_sales.getModel();
                tblmod.addRow(tbdata);
                
                total_row++;
                
            }
            
            con.close();
        }
        catch (SQLException exp) {
            JOptionPane.showMessageDialog(null, exp);
        }
        
        Double total_cost = 0.0;
        Double due;
        
        for(int count = 0; count < total_row; count++){
            total_cost = Double.parseDouble(table_sales.getValueAt(count, 8).toString()) + total_cost;
        }
        
        due = total_cost - Double.parseDouble(label_payment_gen.getText());
        
        label_total_gen.setText(total_cost.toString());
        label_due_gen.setText(due.toString());
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_goback;
    private javax.swing.JButton button_ok;
    private javax.swing.JComboBox<String> combobox_pay_full;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_client;
    private javax.swing.JLabel label_client_gen;
    private javax.swing.JLabel label_client_name;
    private javax.swing.JLabel label_client_name_gen;
    private javax.swing.JLabel label_due;
    private javax.swing.JLabel label_due_gen;
    private javax.swing.JLabel label_emp;
    private javax.swing.JLabel label_emp_gen;
    private javax.swing.JLabel label_full_pay;
    private javax.swing.JLabel label_order_date;
    private javax.swing.JLabel label_order_date_gen;
    private javax.swing.JLabel label_payment;
    private javax.swing.JLabel label_payment_gen;
    private javax.swing.JLabel label_receipt;
    private javax.swing.JLabel label_receipt_gen;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_total;
    private javax.swing.JLabel label_total_gen;
    private javax.swing.JTable table_sales;
    // End of variables declaration//GEN-END:variables
}
